apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cons-prosp
spec:
  rules:
    - host: juvenal.example.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: exemplo-nginx
                port:
                  number: 80
